import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../theme/tokens.stylex";

const pulse = stylex.keyframes({
  "0%, 100%": { opacity: 0.45 },
  "50%": { opacity: 0.9 },
});

const REDUCED_MOTION = "@media (prefers-reduced-motion: reduce)";

export const parts = stylex.create({
  root: {
    color: tokens["--dowel-text-primary"],
    fontFamily: tokens["--dowel-font-sans"],
    minWidth: 0,
    overflowX: "auto",
    overscrollBehaviorInline: "contain",
    scrollbarGutter: "stable",
    width: "100%",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: "0 1px",
    tableLayout: "fixed",
  },
  headerRow: {
    backgroundColor: "transparent",
  },
  stickyHeader: {
    backgroundColor: tokens["--dowel-bg-surface-1"],
    insetBlockStart: 0,
    position: "sticky",
    zIndex: 4,
  },
  headerCell: {
    boxSizing: "border-box",
    color: tokens["--dowel-text-tertiary"],
    fontSize: "0.6875rem",
    fontWeight: 500,
    height: "1.875rem",
    letterSpacing: "0.01em",
    paddingBlock: 0,
    paddingInline: "0.5rem",
    position: "relative",
    textAlign: "left",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  },
  pinnedHeaderCell: {
    backgroundColor: tokens["--dowel-bg-surface-1"],
    position: "sticky",
    zIndex: 5,
  },
  headerButton: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-sm"],
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    font: "inherit",
    gap: "0.25rem",
    height: "1.5rem",
    justifyContent: "inherit",
    marginInline: "-0.25rem",
    maxWidth: "calc(100% + 0.5rem)",
    outline: "none",
    overflow: "hidden",
    paddingInline: "0.25rem",
    textAlign: "inherit",
    whiteSpace: "nowrap",
    ":hover": {
      color: tokens["--dowel-text-secondary"],
      backgroundColor: tokens["--dowel-bg-hover"],
    },
    ":focus-visible": {
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
      color: tokens["--dowel-text-primary"],
    },
  },
  headerLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  sortIcon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "1rem",
    justifyContent: "center",
    opacity: 0,
    transitionDuration: tokens["--dowel-duration-fast"],
    transitionProperty: "opacity, transform",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    width: "1rem",
  },
  sorted: {
    opacity: 1,
  },
  descending: {
    transform: "rotate(180deg)",
  },
  resizeHandle: {
    backgroundColor: "transparent",
    borderStyle: "none",
    cursor: "col-resize",
    height: "1.25rem",
    outline: "none",
    padding: 0,
    position: "absolute",
    right: "-0.25rem",
    top: "50%",
    touchAction: "none",
    transform: "translateY(-50%)",
    userSelect: "none",
    width: "0.5rem",
    zIndex: 1,
    "::after": {
      backgroundColor: "transparent",
      content: '""',
      height: "0.875rem",
      left: "50%",
      position: "absolute",
      top: "50%",
      transform: "translate(-50%, -50%)",
      width: tokens["--dowel-hairline"],
    },
    ":hover": {
      "::after": {
        backgroundColor: tokens["--dowel-border-strong"],
      },
    },
    ":focus-visible": {
      "::after": {
        backgroundColor: tokens["--dowel-focus-ring"],
        width: "1px",
      },
    },
    "[data-resizing]": {
      "::after": {
        backgroundColor: tokens["--dowel-focus-ring"],
        width: "1px",
      },
    },
  },
  row: {
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-md"],
    outline: "none",
    transitionDuration: tokens["--dowel-duration-fast"],
    transitionProperty: "background-color",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    ":hover": {
      backgroundColor: tokens["--dowel-bg-row-hover"],
    },
    ":focus-visible": {
      backgroundColor: tokens["--dowel-bg-row-hover"],
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
    },
    "[data-selected]": {
      backgroundColor: tokens["--dowel-bg-active"],
    },
    "[data-actionable]": {
      cursor: "pointer",
    },
  },
  cell: {
    backgroundColor: "inherit",
    boxSizing: "border-box",
    color: tokens["--dowel-text-primary"],
    fontSize: "0.8125rem",
    fontWeight: 500,
    letterSpacing: "-0.005rem",
    lineHeight: 1.2,
    paddingBlock: 0,
    paddingInline: "0.375rem",
    textAlign: "left",
    verticalAlign: "middle",
    ":first-child": {
      borderBottomLeftRadius: tokens["--dowel-radius-md"],
      borderTopLeftRadius: tokens["--dowel-radius-md"],
    },
    ":last-child": {
      borderBottomRightRadius: tokens["--dowel-radius-md"],
      borderTopRightRadius: tokens["--dowel-radius-md"],
    },
  },
  pinnedCell: {
    position: "sticky",
    zIndex: 2,
  },
  pinnedStartEdge: {
    borderInlineEndColor: tokens["--dowel-border-default"],
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: tokens["--dowel-hairline"],
  },
  pinnedEndEdge: {
    borderInlineStartColor: tokens["--dowel-border-default"],
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: tokens["--dowel-hairline"],
  },
  compactCell: {
    height: "2.5rem",
  },
  comfortableCell: {
    height: "3.25rem",
  },
  cellContent: {
    alignItems: "center",
    display: "flex",
    minWidth: 0,
    width: "100%",
  },
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  selectionCell: {
    paddingInline: "0.375rem",
  },
  groupRow: {
    backgroundColor: "transparent",
  },
  groupCell: {
    backgroundColor: tokens["--dowel-bg-surface-1"],
    borderRadius: tokens["--dowel-radius-md"],
    boxSizing: "border-box",
    boxShadow: `inset 0 0 0 ${tokens["--dowel-hairline"]} ${tokens["--dowel-border-subtle"]}`,
    padding: "0.125rem 0.375rem",
  },
  groupButton: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-sm"],
    color: tokens["--dowel-text-secondary"],
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    fontWeight: 550,
    gap: "0.25rem",
    height: "1.75rem",
    maxWidth: "100%",
    outline: "none",
    paddingInline: "0.25rem 0.5rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
      color: tokens["--dowel-text-primary"],
    },
  },
  groupChevron: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "0.75rem",
    justifyContent: "center",
    width: "0.75rem",
  },
  groupChevronExpanded: {
    transform: "rotate(90deg)",
  },
  groupChevronGlyph: {
    backgroundColor: "currentColor",
    clipPath: "polygon(15% 10%, 85% 50%, 15% 90%)",
    display: "block",
    height: "0.5rem",
    width: "0.4375rem",
  },
  groupLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  groupCount: {
    color: tokens["--dowel-text-tertiary"],
    fontSize: "0.6875rem",
    fontWeight: 450,
  },
  alignCenter: {
    justifyContent: "center",
    textAlign: "center",
  },
  alignEnd: {
    justifyContent: "flex-end",
    textAlign: "right",
  },
  secondary: {
    color: tokens["--dowel-text-secondary"],
  },
  tertiary: {
    color: tokens["--dowel-text-tertiary"],
  },
  mono: {
    fontFamily: tokens["--dowel-font-mono"],
    fontSize: "0.75rem",
    letterSpacing: "-0.01em",
  },
  checkboxLabel: {
    alignItems: "center",
    cursor: "pointer",
    display: "inline-flex",
    height: "1.5rem",
    justifyContent: "center",
    position: "relative",
    width: "1.5rem",
  },
  checkboxInput: {
    height: "1px",
    margin: 0,
    opacity: 0,
    overflow: "hidden",
    position: "absolute",
    width: "1px",
  },
  checkboxVisual: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: tokens["--dowel-border-strong"],
    borderRadius: tokens["--dowel-radius-sm"],
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    color: tokens["--dowel-on-accent"],
    display: "inline-flex",
    height: "1rem",
    justifyContent: "center",
    transitionDuration: tokens["--dowel-duration-fast"],
    transitionProperty: "background-color, border-color, box-shadow",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    width: "1rem",
  },
  checkboxChecked: {
    backgroundColor: tokens["--dowel-accent"],
    borderColor: tokens["--dowel-accent"],
  },
  checkboxDisabled: {
    cursor: "not-allowed",
    opacity: 0.5,
  },
  checkboxFocus: {
    boxShadow: `0 0 0 2px ${tokens["--dowel-bg-surface-1"]}, 0 0 0 3px ${tokens["--dowel-focus-ring"]}`,
  },
  emptyCell: {
    color: tokens["--dowel-text-secondary"],
    padding: "2.5rem 1rem",
    textAlign: "center",
  },
  emptyTitle: {
    color: tokens["--dowel-text-primary"],
    fontSize: "0.8125rem",
    fontWeight: 500,
    margin: 0,
  },
  emptyDescription: {
    color: tokens["--dowel-text-tertiary"],
    fontSize: "0.75rem",
    lineHeight: 1.5,
    margin: "0.25rem auto 0",
    maxWidth: "28rem",
  },
  skeleton: {
    animationDuration: "1.5s",
    animationIterationCount: "infinite",
    animationName: pulse,
    animationTimingFunction: "ease-in-out",
    backgroundColor: tokens["--dowel-bg-surface-3"],
    borderRadius: tokens["--dowel-radius-pill"],
    display: "block",
    height: "0.375rem",
    maxWidth: "12rem",
    width: "68%",
    [REDUCED_MOTION]: {
      animationName: "none",
    },
  },
  visuallyHidden: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});
