import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../theme/tokens.stylex";
export const upload = stylex.create({
  root: { display: "grid", gap: "0.5rem", width: "100%" },
  dropzone: {
    alignItems: "center",
    backgroundColor: tokens["--dowel-bg-surface-2"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-md"],
    borderStyle: "dashed",
    borderWidth: "1px",
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    justifyContent: "center",
    minHeight: "8rem",
    padding: "1rem",
    transitionDuration: tokens["--dowel-duration-fast"],
    transitionProperty: "background-color, border-color",
  },
  dragging: {
    backgroundColor: tokens["--dowel-bg-active"],
    borderColor: tokens["--dowel-accent"],
  },
  disabled: { opacity: 0.55 },
  input: {
    border: 0,
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  browse: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-sm"],
    borderWidth: 0,
    color: tokens["--dowel-text-primary"],
    display: "inline-flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    fontWeight: 500,
    gap: "0.5rem",
    minHeight: "2rem",
    outline: "none",
    paddingInline: "0.5rem",
    ":hover": { backgroundColor: tokens["--dowel-bg-hover"] },
    ":focus-visible": {
      outlineColor: tokens["--dowel-focus-ring"],
      outlineStyle: "solid",
      outlineWidth: "1px",
    },
  },
  description: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    textAlign: "center",
  },
  list: {
    display: "grid",
    gap: "0.25rem",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  file: {
    alignItems: "center",
    backgroundColor: tokens["--dowel-bg-surface-2"],
    borderRadius: tokens["--dowel-radius-sm"],
    display: "flex",
    gap: "0.5rem",
    minHeight: "2rem",
    padding: "0.25rem 0.375rem 0.25rem 0.5rem",
  },
  fileIcon: { color: tokens["--dowel-text-tertiary"], flexShrink: 0 },
  fileName: {
    color: tokens["--dowel-text-primary"],
    flex: 1,
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileSize: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-mono"],
    fontSize: "0.6875rem",
  },
  remove: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-sm"],
    borderWidth: 0,
    color: tokens["--dowel-text-tertiary"],
    display: "inline-flex",
    height: "1.5rem",
    justifyContent: "center",
    outline: "none",
    width: "1.5rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      outlineColor: tokens["--dowel-focus-ring"],
      outlineStyle: "solid",
      outlineWidth: "1px",
    },
  },
});
