/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsAlertDialogRouteImport } from './routes/components/alert-dialog'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsCalloutRouteImport } from './routes/components/callout'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsComposerRouteImport } from './routes/components/composer'
import { Route as ComponentsDataTableRouteImport } from './routes/components/data-table'
import { Route as ComponentsDialogRouteImport } from './routes/components/dialog'
import { Route as ComponentsEmptyStateRouteImport } from './routes/components/empty-state'
import { Route as ComponentsIconButtonRouteImport } from './routes/components/icon-button'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsKbdRouteImport } from './routes/components/kbd'
import { Route as ComponentsMenuRouteImport } from './routes/components/menu'
import { Route as ComponentsNativeSelectRouteImport } from './routes/components/native-select'
import { Route as ComponentsPopoverRouteImport } from './routes/components/popover'
import { Route as ComponentsPropertyPickerRouteImport } from './routes/components/property-picker'
import { Route as ComponentsRadioGroupRouteImport } from './routes/components/radio-group'
import { Route as ComponentsSearchFieldRouteImport } from './routes/components/search-field'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSeparatorRouteImport } from './routes/components/separator'
import { Route as ComponentsSidebarRouteImport } from './routes/components/sidebar'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'
import { Route as ComponentsStatusRouteImport } from './routes/components/status'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsAlertDialogRoute = ComponentsAlertDialogRouteImport.update({
  id: '/alert-dialog',
  path: '/alert-dialog',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCalloutRoute = ComponentsCalloutRouteImport.update({
  id: '/callout',
  path: '/callout',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsComposerRoute = ComponentsComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsDataTableRoute = ComponentsDataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsEmptyStateRoute = ComponentsEmptyStateRouteImport.update({
  id: '/empty-state',
  path: '/empty-state',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsIconButtonRoute = ComponentsIconButtonRouteImport.update({
  id: '/icon-button',
  path: '/icon-button',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsKbdRoute = ComponentsKbdRouteImport.update({
  id: '/kbd',
  path: '/kbd',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsMenuRoute = ComponentsMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsNativeSelectRoute = ComponentsNativeSelectRouteImport.update({
  id: '/native-select',
  path: '/native-select',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsPopoverRoute = ComponentsPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsPropertyPickerRoute =
  ComponentsPropertyPickerRouteImport.update({
    id: '/property-picker',
    path: '/property-picker',
    getParentRoute: () => ComponentsRouteRoute,
  } as any)
const ComponentsRadioGroupRoute = ComponentsRadioGroupRouteImport.update({
  id: '/radio-group',
  path: '/radio-group',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSearchFieldRoute = ComponentsSearchFieldRouteImport.update({
  id: '/search-field',
  path: '/search-field',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSeparatorRoute = ComponentsSeparatorRouteImport.update({
  id: '/separator',
  path: '/separator',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSidebarRoute = ComponentsSidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsStatusRoute = ComponentsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/dependencies': typeof DependenciesRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/callout': typeof ComponentsCalloutRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/composer': typeof ComponentsComposerRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/empty-state': typeof ComponentsEmptyStateRoute
  '/components/icon-button': typeof ComponentsIconButtonRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/kbd': typeof ComponentsKbdRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/native-select': typeof ComponentsNativeSelectRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/property-picker': typeof ComponentsPropertyPickerRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/search-field': typeof ComponentsSearchFieldRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/status': typeof ComponentsStatusRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dependencies': typeof DependenciesRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/callout': typeof ComponentsCalloutRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/composer': typeof ComponentsComposerRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/empty-state': typeof ComponentsEmptyStateRoute
  '/components/icon-button': typeof ComponentsIconButtonRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/kbd': typeof ComponentsKbdRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/native-select': typeof ComponentsNativeSelectRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/property-picker': typeof ComponentsPropertyPickerRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/search-field': typeof ComponentsSearchFieldRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/status': typeof ComponentsStatusRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/dependencies': typeof DependenciesRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/callout': typeof ComponentsCalloutRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/composer': typeof ComponentsComposerRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/empty-state': typeof ComponentsEmptyStateRoute
  '/components/icon-button': typeof ComponentsIconButtonRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/kbd': typeof ComponentsKbdRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/native-select': typeof ComponentsNativeSelectRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/property-picker': typeof ComponentsPropertyPickerRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/search-field': typeof ComponentsSearchFieldRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/status': typeof ComponentsStatusRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/dependencies'
    | '/components/alert-dialog'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button'
    | '/components/callout'
    | '/components/checkbox'
    | '/components/composer'
    | '/components/data-table'
    | '/components/dialog'
    | '/components/empty-state'
    | '/components/icon-button'
    | '/components/input'
    | '/components/kbd'
    | '/components/menu'
    | '/components/native-select'
    | '/components/popover'
    | '/components/property-picker'
    | '/components/radio-group'
    | '/components/search-field'
    | '/components/select'
    | '/components/separator'
    | '/components/sidebar'
    | '/components/skeleton'
    | '/components/spinner'
    | '/components/status'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tooltip'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dependencies'
    | '/components/alert-dialog'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button'
    | '/components/callout'
    | '/components/checkbox'
    | '/components/composer'
    | '/components/data-table'
    | '/components/dialog'
    | '/components/empty-state'
    | '/components/icon-button'
    | '/components/input'
    | '/components/kbd'
    | '/components/menu'
    | '/components/native-select'
    | '/components/popover'
    | '/components/property-picker'
    | '/components/radio-group'
    | '/components/search-field'
    | '/components/select'
    | '/components/separator'
    | '/components/sidebar'
    | '/components/skeleton'
    | '/components/spinner'
    | '/components/status'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tooltip'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/dependencies'
    | '/components/alert-dialog'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button'
    | '/components/callout'
    | '/components/checkbox'
    | '/components/composer'
    | '/components/data-table'
    | '/components/dialog'
    | '/components/empty-state'
    | '/components/icon-button'
    | '/components/input'
    | '/components/kbd'
    | '/components/menu'
    | '/components/native-select'
    | '/components/popover'
    | '/components/property-picker'
    | '/components/radio-group'
    | '/components/search-field'
    | '/components/select'
    | '/components/separator'
    | '/components/sidebar'
    | '/components/skeleton'
    | '/components/spinner'
    | '/components/status'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tooltip'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
  DependenciesRoute: typeof DependenciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/alert-dialog': {
      id: '/components/alert-dialog'
      path: '/alert-dialog'
      fullPath: '/components/alert-dialog'
      preLoaderRoute: typeof ComponentsAlertDialogRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/callout': {
      id: '/components/callout'
      path: '/callout'
      fullPath: '/components/callout'
      preLoaderRoute: typeof ComponentsCalloutRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/composer': {
      id: '/components/composer'
      path: '/composer'
      fullPath: '/components/composer'
      preLoaderRoute: typeof ComponentsComposerRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/data-table': {
      id: '/components/data-table'
      path: '/data-table'
      fullPath: '/components/data-table'
      preLoaderRoute: typeof ComponentsDataTableRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/empty-state': {
      id: '/components/empty-state'
      path: '/empty-state'
      fullPath: '/components/empty-state'
      preLoaderRoute: typeof ComponentsEmptyStateRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/icon-button': {
      id: '/components/icon-button'
      path: '/icon-button'
      fullPath: '/components/icon-button'
      preLoaderRoute: typeof ComponentsIconButtonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/input': {
      id: '/components/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/kbd': {
      id: '/components/kbd'
      path: '/kbd'
      fullPath: '/components/kbd'
      preLoaderRoute: typeof ComponentsKbdRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/native-select': {
      id: '/components/native-select'
      path: '/native-select'
      fullPath: '/components/native-select'
      preLoaderRoute: typeof ComponentsNativeSelectRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/popover': {
      id: '/components/popover'
      path: '/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/property-picker': {
      id: '/components/property-picker'
      path: '/property-picker'
      fullPath: '/components/property-picker'
      preLoaderRoute: typeof ComponentsPropertyPickerRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/radio-group': {
      id: '/components/radio-group'
      path: '/radio-group'
      fullPath: '/components/radio-group'
      preLoaderRoute: typeof ComponentsRadioGroupRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/search-field': {
      id: '/components/search-field'
      path: '/search-field'
      fullPath: '/components/search-field'
      preLoaderRoute: typeof ComponentsSearchFieldRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/select': {
      id: '/components/select'
      path: '/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/separator': {
      id: '/components/separator'
      path: '/separator'
      fullPath: '/components/separator'
      preLoaderRoute: typeof ComponentsSeparatorRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/sidebar': {
      id: '/components/sidebar'
      path: '/sidebar'
      fullPath: '/components/sidebar'
      preLoaderRoute: typeof ComponentsSidebarRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/status': {
      id: '/components/status'
      path: '/status'
      fullPath: '/components/status'
      preLoaderRoute: typeof ComponentsStatusRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
  }
}

interface ComponentsRouteRouteChildren {
  ComponentsAlertDialogRoute: typeof ComponentsAlertDialogRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCalloutRoute: typeof ComponentsCalloutRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsComposerRoute: typeof ComponentsComposerRoute
  ComponentsDataTableRoute: typeof ComponentsDataTableRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsEmptyStateRoute: typeof ComponentsEmptyStateRoute
  ComponentsIconButtonRoute: typeof ComponentsIconButtonRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsKbdRoute: typeof ComponentsKbdRoute
  ComponentsMenuRoute: typeof ComponentsMenuRoute
  ComponentsNativeSelectRoute: typeof ComponentsNativeSelectRoute
  ComponentsPopoverRoute: typeof ComponentsPopoverRoute
  ComponentsPropertyPickerRoute: typeof ComponentsPropertyPickerRoute
  ComponentsRadioGroupRoute: typeof ComponentsRadioGroupRoute
  ComponentsSearchFieldRoute: typeof ComponentsSearchFieldRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSeparatorRoute: typeof ComponentsSeparatorRoute
  ComponentsSidebarRoute: typeof ComponentsSidebarRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsStatusRoute: typeof ComponentsStatusRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsAlertDialogRoute: ComponentsAlertDialogRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCalloutRoute: ComponentsCalloutRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsComposerRoute: ComponentsComposerRoute,
  ComponentsDataTableRoute: ComponentsDataTableRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsEmptyStateRoute: ComponentsEmptyStateRoute,
  ComponentsIconButtonRoute: ComponentsIconButtonRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsKbdRoute: ComponentsKbdRoute,
  ComponentsMenuRoute: ComponentsMenuRoute,
  ComponentsNativeSelectRoute: ComponentsNativeSelectRoute,
  ComponentsPopoverRoute: ComponentsPopoverRoute,
  ComponentsPropertyPickerRoute: ComponentsPropertyPickerRoute,
  ComponentsRadioGroupRoute: ComponentsRadioGroupRoute,
  ComponentsSearchFieldRoute: ComponentsSearchFieldRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSeparatorRoute: ComponentsSeparatorRoute,
  ComponentsSidebarRoute: ComponentsSidebarRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsStatusRoute: ComponentsStatusRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
  DependenciesRoute: DependenciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
