import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../theme/tokens.stylex";

const MOBILE = "@media (max-width: 639px)";
const REDUCED_MOTION = "@media (prefers-reduced-motion: reduce)";

export const command = stylex.create({
  title: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  backdrop: {
    backgroundColor: tokens["--dowel-scrim"],
    inset: 0,
    opacity: 1,
    position: "fixed",
    transitionDuration: {
      default: tokens["--dowel-duration-normal"],
      [REDUCED_MOTION]: "0.01ms",
    },
    transitionProperty: "opacity",
    zIndex: 60,
    "[data-starting-style]": { opacity: 0 },
    "[data-ending-style]": { opacity: 0 },
  },
  popup: {
    backgroundColor: tokens["--dowel-bg-elevated"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: {
      default: tokens["--dowel-radius-lg"],
      [MOBILE]: tokens["--dowel-radius-md"],
    },
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-modal"],
    boxSizing: "border-box",
    color: tokens["--dowel-text-primary"],
    insetBlockStart: { default: "max(3rem, 15vh)", [MOBILE]: "0.5rem" },
    insetInlineStart: "50%",
    maxHeight: {
      default: "min(32rem, calc(100dvh - 6rem))",
      [MOBILE]: "calc(100dvh - 1rem)",
    },
    opacity: 1,
    outline: "none",
    overflow: "hidden",
    position: "fixed",
    transform: "translateX(-50%)",
    transitionDuration: {
      default: tokens["--dowel-duration-normal"],
      [REDUCED_MOTION]: "0.01ms",
    },
    transitionProperty: "opacity, translate",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    translate: "0 0",
    width: {
      default: "min(38rem, calc(100vw - 2rem))",
      [MOBILE]: "calc(100vw - 1rem)",
    },
    zIndex: 61,
    "[data-starting-style]": { opacity: 0, translate: "0 -0.25rem" },
    "[data-ending-style]": { opacity: 0, translate: "0 -0.25rem" },
  },
  search: {
    alignItems: "center",
    borderBottomColor: tokens["--dowel-border-subtle"],
    borderBottomStyle: "solid",
    borderBottomWidth: tokens["--dowel-hairline"],
    display: "flex",
    gap: "0.625rem",
    minHeight: "3rem",
    paddingInline: "0.875rem",
  },
  searchIcon: { color: tokens["--dowel-text-tertiary"], flexShrink: 0 },
  input: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: tokens["--dowel-text-primary"],
    flex: 1,
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: { default: "0.9375rem", [MOBILE]: "1rem" },
    height: "3rem",
    minWidth: 0,
    outline: "none",
    padding: 0,
    "::placeholder": { color: tokens["--dowel-text-tertiary"] },
  },
  list: { maxHeight: "26rem", overflowY: "auto", padding: "0.375rem" },
  groupLabel: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.6875rem",
    fontWeight: 550,
    lineHeight: 1.4,
    padding: "0.5rem 0.5rem 0.25rem",
  },
  item: {
    alignItems: "center",
    borderRadius: tokens["--dowel-radius-sm"],
    cursor: "default",
    display: "flex",
    gap: "0.625rem",
    minHeight: "2.5rem",
    outline: "none",
    padding: "0.375rem 0.5rem",
    "[data-highlighted]": { backgroundColor: tokens["--dowel-bg-hover"] },
    "[data-disabled]": { color: tokens["--dowel-text-disabled"] },
  },
  itemIcon: {
    alignItems: "center",
    color: tokens["--dowel-text-tertiary"],
    display: "inline-flex",
    flexShrink: 0,
  },
  itemCopy: { display: "flex", flex: 1, flexDirection: "column", minWidth: 0 },
  itemLabel: {
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDescription: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shortcut: {
    color: tokens["--dowel-text-tertiary"],
    flexShrink: 0,
    fontFamily: tokens["--dowel-font-mono"],
    fontSize: "0.6875rem",
    lineHeight: 1.4,
  },
  empty: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    padding: "2rem 1rem",
    textAlign: "center",
  },
  footer: {
    alignItems: "center",
    borderTopColor: tokens["--dowel-border-subtle"],
    borderTopStyle: "solid",
    borderTopWidth: tokens["--dowel-hairline"],
    color: tokens["--dowel-text-tertiary"],
    display: "flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.6875rem",
    gap: "0.75rem",
    justifyContent: "flex-end",
    minHeight: "2rem",
    padding: "0.375rem 0.75rem",
  },
});
