import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../theme/tokens.stylex";

export const panel = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    minWidth: "17rem",
  },
  header: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    paddingBlockEnd: "0.5rem",
  },
  reset: {
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-sm"],
    color: tokens["--dowel-text-tertiary"],
    cursor: "pointer",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    height: tokens["--dowel-control-sm"],
    outline: "none",
    paddingInline: "0.375rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
    },
  },
  section: {
    borderBlockStartColor: tokens["--dowel-border-subtle"],
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: tokens["--dowel-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    paddingBlock: "0.75rem",
  },
  row: {
    alignItems: "center",
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: "minmax(0, 1fr) 9rem",
  },
  rowLabel: {
    color: tokens["--dowel-text-secondary"],
    fontSize: "0.8125rem",
    fontWeight: 500,
  },
  control: {
    minWidth: 0,
    position: "relative",
  },
  choiceTrigger: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: tokens["--dowel-bg-surface-1"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-md"],
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-control"],
    color: tokens["--dowel-text-primary"],
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    fontWeight: 450,
    gap: "0.375rem",
    height: tokens["--dowel-control-sm"],
    justifyContent: "space-between",
    minWidth: 0,
    outline: "none",
    paddingInline: "0.625rem 0.5rem",
    textAlign: "left",
    width: "100%",
    ":hover": {
      borderColor: tokens["--dowel-border-strong"],
    },
    ":focus-visible": {
      borderColor: tokens["--dowel-focus-ring"],
    },
  },
  choiceValue: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  choiceChevron: {
    color: tokens["--dowel-text-tertiary"],
    flexShrink: 0,
    transitionDuration: tokens["--dowel-duration-fast"],
    transitionProperty: "transform",
    transitionTimingFunction: tokens["--dowel-ease-out"],
  },
  choiceChevronOpen: {
    transform: "rotate(180deg)",
  },
  choicePopup: {
    backgroundColor: tokens["--dowel-bg-elevated"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-md"],
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-popover"],
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
    insetInline: 0,
    padding: "0.25rem",
    position: "absolute",
    top: "calc(100% + 0.25rem)",
    zIndex: 2,
  },
  choiceOption: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-sm"],
    color: tokens["--dowel-text-secondary"],
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    gap: "0.5rem",
    justifyContent: "space-between",
    minHeight: "1.75rem",
    outline: "none",
    paddingInline: "0.5rem",
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      backgroundColor: tokens["--dowel-bg-active"],
      color: tokens["--dowel-text-primary"],
    },
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.45,
    },
  },
  properties: {
    borderBlockStartColor: tokens["--dowel-border-subtle"],
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: tokens["--dowel-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    paddingBlockStart: "0.75rem",
  },
  sectionLabel: {
    color: tokens["--dowel-text-secondary"],
    fontSize: "0.8125rem",
    fontWeight: 500,
  },
  pills: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
  },
});
