import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../theme/tokens.stylex";

const REDUCED_MOTION = "@media (prefers-reduced-motion: reduce)";

export const control = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: tokens["--dowel-bg-surface-1"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-md"],
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-control"],
    boxSizing: "border-box",
    display: "flex",
    height: tokens["--dowel-control-lg"],
    minWidth: "12rem",
    overflow: "hidden",
    ":focus-within": {
      borderColor: tokens["--dowel-focus-ring"],
      outlineColor: tokens["--dowel-focus-ring"],
      outlineOffset: "-1px",
      outlineStyle: "solid",
      outlineWidth: "1px",
    },
    ":has(input:disabled)": {
      backgroundColor: tokens["--dowel-bg-surface-2"],
      color: tokens["--dowel-text-disabled"],
    },
  },
  input: {
    backgroundColor: "transparent",
    borderWidth: 0,
    boxSizing: "border-box",
    color: tokens["--dowel-text-primary"],
    flex: 1,
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.875rem",
    height: "100%",
    lineHeight: 1.4,
    minWidth: 0,
    outline: "none",
    padding: "0 0.625rem",
    "::placeholder": { color: tokens["--dowel-text-tertiary"] },
    ":disabled": { cursor: "not-allowed" },
  },
  actions: {
    alignItems: "center",
    display: "flex",
    paddingInlineEnd: "0.25rem",
  },
  action: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: tokens["--dowel-radius-sm"],
    color: tokens["--dowel-text-tertiary"],
    display: "inline-flex",
    height: "1.75rem",
    justifyContent: "center",
    padding: 0,
    width: "1.75rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      outlineColor: tokens["--dowel-focus-ring"],
      outlineOffset: "-2px",
      outlineStyle: "solid",
      outlineWidth: "2px",
    },
    "[data-disabled]": { cursor: "not-allowed", opacity: 0.5 },
  },
});

export const popup = stylex.create({
  root: {
    backgroundColor: tokens["--dowel-bg-elevated"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-md"],
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-popover"],
    boxSizing: "border-box",
    color: tokens["--dowel-text-primary"],
    maxHeight: "min(20rem, var(--available-height))",
    minWidth: "var(--anchor-width)",
    opacity: 1,
    outline: "none",
    overflow: "hidden",
    transformOrigin: "var(--transform-origin)",
    transitionDuration: {
      default: tokens["--dowel-duration-fast"],
      [REDUCED_MOTION]: "0.01ms",
    },
    transitionProperty: "opacity, scale",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    "[data-starting-style]": { opacity: 0, scale: 0.98 },
    "[data-ending-style]": { opacity: 0, scale: 0.98 },
  },
  list: { maxHeight: "19rem", overflowY: "auto", padding: "0.25rem" },
  groupLabel: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.6875rem",
    fontWeight: 550,
    lineHeight: 1.4,
    padding: "0.5rem 0.5rem 0.25rem",
  },
  item: {
    alignItems: "center",
    borderRadius: tokens["--dowel-radius-sm"],
    boxSizing: "border-box",
    cursor: "default",
    display: "flex",
    gap: "0.5rem",
    minHeight: tokens["--dowel-control-md"],
    outline: "none",
    padding: "0.375rem 0.5rem",
    "[data-highlighted]": { backgroundColor: tokens["--dowel-bg-hover"] },
    "[data-selected]": { color: tokens["--dowel-accent"] },
    "[data-disabled]": { color: tokens["--dowel-text-disabled"] },
  },
  icon: {
    alignItems: "center",
    color: tokens["--dowel-text-tertiary"],
    display: "inline-flex",
    flexShrink: 0,
  },
  copy: { display: "flex", flex: 1, flexDirection: "column", minWidth: 0 },
  label: {
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  description: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  indicator: {
    alignItems: "center",
    color: tokens["--dowel-accent"],
    display: "inline-flex",
    flexShrink: 0,
  },
  empty: {
    color: tokens["--dowel-text-tertiary"],
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.8125rem",
    padding: "1rem",
    textAlign: "center",
  },
});
