import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../theme/tokens.stylex";

export const bar = stylex.create({
  root: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
    minWidth: 0,
  },
  chip: {
    alignItems: "center",
    backgroundColor: tokens["--dowel-bg-surface-2"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-pill"],
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxSizing: "border-box",
    color: tokens["--dowel-text-secondary"],
    display: "inline-flex",
    height: tokens["--dowel-control-md"],
    maxWidth: "18rem",
    minWidth: 0,
  },
  filterButton: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-pill"],
    color: "inherit",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    fontWeight: 500,
    gap: "0.25rem",
    height: "100%",
    minWidth: 0,
    outline: "none",
    paddingInline: "0.5625rem 0.25rem",
    ":hover": {
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
    },
  },
  staticLabel: {
    alignItems: "center",
    display: "inline-flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    fontWeight: 500,
    gap: "0.25rem",
    minWidth: 0,
    paddingInline: "0.5625rem 0.25rem",
  },
  label: {
    flexShrink: 0,
  },
  value: {
    color: tokens["--dowel-text-primary"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  remove: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-pill"],
    color: tokens["--dowel-text-tertiary"],
    cursor: "pointer",
    display: "inline-flex",
    height: "1.25rem",
    justifyContent: "center",
    marginInlineEnd: "0.1875rem",
    outline: "none",
    padding: 0,
    width: "1.25rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
    },
  },
  clear: {
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderRadius: tokens["--dowel-radius-sm"],
    color: tokens["--dowel-text-tertiary"],
    cursor: "pointer",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    height: tokens["--dowel-control-md"],
    outline: "none",
    paddingInline: "0.5rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      boxShadow: `inset 0 0 0 1px ${tokens["--dowel-focus-ring"]}`,
    },
  },
});
