import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../theme/tokens.stylex";

const COARSE = "@media (pointer: coarse)";
const REDUCED_MOTION = "@media (prefers-reduced-motion: reduce)";

export const calendar = stylex.create({
  root: {
    boxSizing: "border-box",
    color: tokens["--dowel-text-primary"],
    fontFamily: tokens["--dowel-font-sans"],
    padding: "0.25rem",
    width: "17.5rem",
  },
  header: {
    alignItems: "center",
    display: "grid",
    gap: "0.25rem",
    gridTemplateColumns: "2rem 1fr 2rem",
    marginBottom: "0.375rem",
  },
  month: {
    fontSize: "0.8125rem",
    fontWeight: 600,
    margin: 0,
    textAlign: "center",
  },
  nav: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-sm"],
    borderWidth: 0,
    color: tokens["--dowel-text-secondary"],
    display: "inline-flex",
    height: "2rem",
    justifyContent: "center",
    outline: "none",
    padding: 0,
    width: "2rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      outlineColor: tokens["--dowel-focus-ring"],
      outlineOffset: "-1px",
      outlineStyle: "solid",
      outlineWidth: "1px",
    },
  },
  grid: {
    borderCollapse: "separate",
    borderSpacing: "0.125rem",
    tableLayout: "fixed",
    width: "100%",
  },
  weekday: {
    color: tokens["--dowel-text-tertiary"],
    fontSize: "0.6875rem",
    fontWeight: 600,
    height: "1.5rem",
    padding: 0,
    textAlign: "center",
    textTransform: "uppercase",
  },
  day: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-sm"],
    boxSizing: "border-box",
    color: tokens["--dowel-text-secondary"],
    cursor: "default",
    display: "flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    height: { default: "2rem", [COARSE]: "2.5rem" },
    justifyContent: "center",
    outline: "none",
    padding: 0,
    position: "relative",
    textAlign: "center",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
  },
  dayFocused: {
    outlineColor: tokens["--dowel-focus-ring"],
    outlineOffset: "-1px",
    outlineStyle: "solid",
    outlineWidth: "1px",
  },
  outside: { color: tokens["--dowel-text-disabled"] },
  selected: {
    backgroundColor: tokens["--dowel-accent"],
    color: tokens["--dowel-on-accent"],
    ":hover": {
      backgroundColor: tokens["--dowel-accent-hover"],
      color: tokens["--dowel-on-accent"],
    },
  },
  today: {
    fontWeight: 700,
    "::after": {
      backgroundColor: tokens["--dowel-accent"],
      borderRadius: "50%",
      bottom: "0.1875rem",
      content: '""',
      height: "2px",
      left: "calc(50% - 1px)",
      position: "absolute",
      width: "2px",
    },
  },
  todaySelected: {
    "::after": { backgroundColor: tokens["--dowel-on-accent"] },
  },
  disabled: {
    color: tokens["--dowel-text-disabled"],
    opacity: 0.45,
  },
  unavailable: {
    color: tokens["--dowel-text-tertiary"],
    textDecoration: "line-through",
  },
});

export const picker = stylex.create({
  root: {
    display: "inline-flex",
    flexDirection: "column",
    fontFamily: tokens["--dowel-font-sans"],
    gap: "0.375rem",
    minWidth: 0,
  },
  label: {
    color: tokens["--dowel-text-primary"],
    fontSize: "0.8125rem",
    fontWeight: 500,
    lineHeight: 1.4,
  },
  group: {
    alignItems: "center",
    backgroundColor: tokens["--dowel-bg-surface-1"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: tokens["--dowel-radius-md"],
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-control"],
    boxSizing: "border-box",
    display: "inline-flex",
    height: tokens["--dowel-control-md"],
    minWidth: "10rem",
    transitionDuration: tokens["--dowel-duration-normal"],
    transitionProperty: "border-color, background-color, opacity",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    ":hover": { borderColor: tokens["--dowel-border-strong"] },
  },
  groupFocused: {
    borderColor: tokens["--dowel-focus-ring"],
    boxShadow: "none",
  },
  groupInvalid: { borderColor: tokens["--dowel-danger"] },
  disabled: { cursor: "not-allowed", opacity: 0.55 },
  input: {
    alignItems: "center",
    color: tokens["--dowel-text-primary"],
    display: "flex",
    flex: 1,
    fontSize: "0.8125rem",
    fontWeight: 450,
    letterSpacing: "-0.0125rem",
    minWidth: 0,
    paddingLeft: "0.625rem",
  },
  segment: {
    borderRadius: "3px",
    color: tokens["--dowel-text-primary"],
    outline: "none",
    paddingBlock: "0.125rem",
    "[data-placeholder]": { color: tokens["--dowel-text-tertiary"] },
    "[data-focused]": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    "[data-type='literal']": { color: tokens["--dowel-text-tertiary"] },
  },
  trigger: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "transparent",
    borderColor: tokens["--dowel-border-subtle"],
    borderRadius: 0,
    borderStyle: "solid",
    borderWidth: "0 0 0 1px",
    color: tokens["--dowel-text-secondary"],
    display: "inline-flex",
    justifyContent: "center",
    outline: "none",
    padding: 0,
    width: "2rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
  },
  description: {
    color: tokens["--dowel-text-tertiary"],
    fontSize: "0.75rem",
    lineHeight: 1.5,
  },
  popover: {
    backgroundColor: tokens["--dowel-bg-elevated"],
    borderColor: tokens["--dowel-border-default"],
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: tokens["--dowel-hairline"],
    boxShadow: tokens["--dowel-shadow-popover"],
    boxSizing: "border-box",
    maxWidth: "calc(100vw - 1rem)",
    opacity: 1,
    outline: "none",
    padding: "0.5rem",
    transitionDuration: {
      default: tokens["--dowel-duration-fast"],
      [REDUCED_MOTION]: "0.01ms",
    },
    transitionProperty: "opacity, transform",
    transitionTimingFunction: tokens["--dowel-ease-out"],
    zIndex: 70,
    "[data-entering]": { opacity: 0, transform: "translateY(-2px)" },
    "[data-exiting]": { opacity: 0, transform: "translateY(-2px)" },
  },
  dialog: { outline: "none" },
});
