import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../theme/tokens.stylex";
const COARSE = "@media (pointer: coarse)";
export const calendar = stylex.create({
  root: {
    boxSizing: "border-box",
    color: tokens["--dowel-text-primary"],
    fontFamily: tokens["--dowel-font-sans"],
    padding: "0.25rem",
    width: "17.5rem",
  },
  header: {
    alignItems: "center",
    display: "grid",
    gap: "0.25rem",
    gridTemplateColumns: "2rem 1fr 2rem",
    marginBottom: "0.375rem",
  },
  month: { fontSize: "0.8125rem", fontWeight: 600, textAlign: "center" },
  nav: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-sm"],
    borderWidth: 0,
    color: tokens["--dowel-text-secondary"],
    display: "inline-flex",
    height: "2rem",
    justifyContent: "center",
    outline: "none",
    width: "2rem",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      outlineColor: tokens["--dowel-focus-ring"],
      outlineOffset: "-1px",
      outlineStyle: "solid",
      outlineWidth: "1px",
    },
  },
  grid: {
    display: "grid",
    gap: "0.125rem",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
  },
  weekday: {
    alignItems: "center",
    color: tokens["--dowel-text-tertiary"],
    display: "flex",
    fontSize: "0.6875rem",
    fontWeight: 600,
    height: "1.5rem",
    justifyContent: "center",
    textTransform: "uppercase",
  },
  day: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens["--dowel-radius-sm"],
    borderWidth: 0,
    color: tokens["--dowel-text-secondary"],
    display: "flex",
    fontFamily: tokens["--dowel-font-sans"],
    fontSize: "0.75rem",
    height: { default: "2rem", [COARSE]: "2.5rem" },
    justifyContent: "center",
    outline: "none",
    position: "relative",
    ":hover": {
      backgroundColor: tokens["--dowel-bg-hover"],
      color: tokens["--dowel-text-primary"],
    },
    ":focus-visible": {
      outlineColor: tokens["--dowel-focus-ring"],
      outlineOffset: "-1px",
      outlineStyle: "solid",
      outlineWidth: "1px",
    },
    ":disabled": { color: tokens["--dowel-text-disabled"], opacity: 0.45 },
  },
  outside: { color: tokens["--dowel-text-disabled"] },
  selected: {
    backgroundColor: tokens["--dowel-accent"],
    color: tokens["--dowel-on-accent"],
    ":hover": {
      backgroundColor: tokens["--dowel-accent-hover"],
      color: tokens["--dowel-on-accent"],
    },
  },
  today: {
    fontWeight: 700,
    "::after": {
      backgroundColor: tokens["--dowel-accent"],
      borderRadius: "50%",
      bottom: "0.1875rem",
      content: '""',
      height: "2px",
      left: "calc(50% - 1px)",
      position: "absolute",
      width: "2px",
    },
  },
});
